destination: &dest syn51498092
staging_path: ./staging
gx_folder: syn63141015
gx_table: syn63891939
datasets:
  - biomarkers:
      files:
        - name: biomarkers
          id: syn61250724
          format: csv
      final_format: json
      provenance:
        - syn61250724
      destination: *dest
      custom_transformations: immunohisto_transform
      column_rename:
        agedeath: age_death
      gx_enabled: true
      gx_nested_columns:
        - points

  - pathology:
      files:
        - name: pathology
          id: syn61357279
          format: csv
      final_format: json
      provenance:
        - syn61357279
      destination: *dest
      custom_transformations: immunohisto_transform
      column_rename:
        agedeath: age_death
      gx_enabled: true
      gx_nested_columns:
        - points

  - model_details:
      files:
        - name: model_info
          id: syn61378590
          format: csv
        - name: allele_info
          id: syn64618791
          format: csv
        - name: pathology
          id: syn61357279
          format: csv
        - name: biomarkers
          id: syn61250724
          format: csv
        - name: human_transgene_allele_map
          id: syn64846805
          format: csv
      final_format: json
      provenance:
        - syn61378590
        - syn64618791
        - syn61357279
        - syn61250724
        - syn64846805
      destination: *dest
      custom_transformations: transform_model_details
      column_rename:
        gene_symbol: gene
        ensembl_id: human_ensembl_id
