destination: &dest syn51498092
staging_path: ./staging
gx_folder: syn63141015
gx_table: syn63891939
datasets:
  - biomarkers:
      files:
        - name: biomarkers
          id: syn61250724.1
          format: csv
      final_format: json
      provenance:
        - syn61250724.1
      destination: *dest
      custom_transformations: 1
      column_rename:
        agedeath: age_death
      gx_enabled: true
      gx_nested_columns:
        - points

  - pathology:
      files:
        - name: pathology
          id: syn61357279
          format: csv
      final_format: json
      provenance:
        - syn61357279
      destination: *dest
      custom_transformations: 1
      column_rename:
        agedeath: age_death
      gx_enabled: true
      gx_nested_columns:
        - points
