destination: &dest syn51498088   # prod
staging_path: ./staging
gx_folder: syn63141014           # prod
gx_table: syn71888383            # prod
# Reusable file and column rename reference anchors used by multiple datasets below.
shared:
  files:
    - &model_info                  {name: model_info                 , format: csv  , id: syn61378590.13}
    - &allele_info                 {name: allele_info                , format: csv  , id: syn64618791.6 }
    - &human_transgene_allele_map  {name: human_transgene_allele_map , format: csv  , id: syn64846805.2 }
    - &model_results_info          {name: model_results_info         , format: csv  , id: syn68377668.7 }
    - &rnaseq_genotype_label_map   {name: rnaseq_genotype_label_map  , format: csv  , id: syn69014401.17}
    - &mouse_gene_metadata         {name: mouse_gene_metadata        , format: json , id: syn51615422.4 }
datasets:
  - model_details:
      files:
        - <<: *model_info
        - <<: *allele_info
        - name: pathology
          id: syn61357279.18
          format: csv
        - name: biomarkers
          id: syn61250724.12
          format: csv
        - <<: *human_transgene_allele_map
        - <<: *model_results_info
        - name: immunohisto_measure_order
          id: syn71305327.2
          format: yaml
      final_format: json
      destination: *dest
      custom_transformations: transform_model_details
      column_rename:
        gene: modified_gene
        ensembl_id: human_ensembl_id
        agedeath: age
        age_death: age
        measurement: value
        type: evidence_type
        model: name
        key: dataset_name
        items: evidence_type
      gx_nested_columns:
        - genetic_info
        - biomarkers
        - pathology
      gx_enabled: true

  - disease_correlation:
      files:
        - name: disease_correlation_results
          id: syn65467849.6
          format: csv
        - <<: *model_info
        - <<: *allele_info
        - <<: *human_transgene_allele_map
      final_format: json
      destination: *dest
      custom_transformations: transform_disease_correlation
      column_rename:
        ensembl_id: human_ensembl_id

  - ui_config:
      files:
        - name: ui_config
          id: syn66527739.30
          format: json
      final_format: json
      destination: *dest
      gx_enabled: true
      gx_nested_columns:
        - columns

  - model_overview:
      files:
        - <<: *model_info
        - <<: *model_results_info
        - <<: *allele_info
        - <<: *human_transgene_allele_map
      final_format: json
      destination: *dest
      custom_transformations: transform_model_overview
      column_rename:
        gene: modified_gene
        ensembl_id: human_ensembl_id
        model: name
      gx_enabled: true
      gx_nested_columns:
        - transcriptomics
        - disease_correlation
        - pathology
        - biomarkers
        - study_data
        - jax_strain

  - rna_de_aggregate:
      files:
        - <<: *rnaseq_genotype_label_map
        - <<: *mouse_gene_metadata
        - name: biodom_genes_mm
          id: syn66351272.1
          format: csv
        - name: Jax.IU.Pitt_5XFAD_differential_expression
          id: syn69058660.2
          format: csv
        - name: Jax.IU.Pitt_APOE4.Trem2.R47H_differential_expression
          id: syn69693082.3
          format: csv
        - name: UCI_3xTg-AD_differential_expression
          id: syn69058661.2
          format: csv
        - name: UCI_5XFAD_differential_expression
          id: syn69058664.1
          format: csv
        - name: UCI_ABCA7_differential_expression
          id: syn69058663.3
          format: csv
        - name: UCI_Trem2-R47H_NSS_differential_expression
          id: syn69058662.3
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: transform_rna_de_aggregate

  - rna_de_individual:
      files:
        - <<: *rnaseq_genotype_label_map
        - <<: *mouse_gene_metadata
        - name: Jax.IU.Pitt_APOE4.Trem2.R47H_normalized_expression
          id: syn72388432.1
          format: csv
        - name: Jax.IU.Pitt_APOE4_normalized_expression
          id: syn72388431.2
          format: csv
        - name: Jax.IU.Pitt_Trem2.R47H_normalized_expression
          id: syn72388430.2
          format: csv
        - name: UCI_ABCA7.5XFAD_normalized_expression
          id: syn72388476.2
          format: csv
        - name: UCI_ABCA7_normalized_expression
          id: syn72388477.1
          format: csv
        - name: UCI_Trem2-R47H_NSS.5XFAD_normalized_expression
          id: syn72388499.2
          format: csv
        - name: UCI_Trem2-R47H_NSS_normalized_expression
          id: syn72388498.1
          format: csv
        - name: UCI_3xTg-AD_normalized_expression
          id: syn69058676.1
          format: csv
        - name: UCI_5XFAD_normalized_expression
          id: syn69058679.1
          format: csv
        - name: Jax.IU.Pitt_5XFAD_normalized_expression
          id: syn69058674.1
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: transform_rna_de_individual
