destination: &dest syn51498091 # preprod
staging_path: ./staging
gx_folder: syn59934608         # preprod
gx_table: syn71888382          # preprod
# Reusable file reference anchors used by datasets below.
files:
  # Metadata & Configuration
  - &model_genetic_modifications  { name: model_genetic_modifications  , format: csv  , id: syn76147521.5  }
  - &immunohisto_measure_order    { name: immunohisto_measure_order    , format: yaml , id: syn71305327.2  }
  - &model_metadata               { name: model_metadata               , format: csv  , id: syn76069176.6  }
  - &mouse_gene_metadata          { name: mouse_gene_metadata          , format: json , id: syn51615422.6  }
  - &genotype_label_map           { name: genotype_label_map           , format: csv  , id: syn69014401.19 }
  - &ui_config                    { name: ui_config                    , format: json , id: syn66527739 }
  # Results
  - &biodom_genes_mm              { name: biodom_genes_mm              , format: csv  , id: syn66351272.1  }
  - &biomarkers                   { name: biomarkers                   , format: csv  , id: syn61250724.12 }
  - &disease_correlation_results  { name: disease_correlation_results  , format: csv  , id: syn65467849.6  }
  - &pathology                    { name: pathology                    , format: csv  , id: syn61357279.18 }
  # Differential Expression Results
  - &jax_5xFAD_de                 { name: jax_5xFAD_de                 , format: csv  , id: syn69058660.2  }
  - &jax_APOE4_Trem2_R47H_de      { name: jax_APOE4_Trem2_R47H_de      , format: csv  , id: syn76459470.1  } #syn69693082.4 when released to portal
  - &jax_LOAD2_de                 { name: jax_LOAD2_de                 , format: csv  , id: syn76459572.1  }
  - &uci_3xTG_AD_de               { name: uci_3xTG_AD_de               , format: csv  , id: syn69058661.2  }
  - &uci_5xFAD_de                 { name: uci_5xFAD_de                 , format: csv  , id: syn69058664.1  }
  - &uci_ABCA7_de                 { name: uci_ABCA7_de                 , format: csv  , id: syn69058663.3  }
  - &uci_Bin1_de                  { name: uci_Bin1_de                  , format: csv  , id: syn76457207.1  }
  - &uci_Clu_de                   { name: uci_Clu_de                   , format: csv  , id: syn76457215.2  }
  - &uci_Trem2_R47H_NSS_de        { name: uci_Trem2_R47H_NSS_de        , format: csv  , id: syn69058662.3  }
  # Normalized Expression Results
  - &jax_5xFAD_ne                 { name: jax_5xFAD_ne                 , format: csv  , id: syn69058674.1  }
  - &jax_APOE4_ne                 { name: jax_APOE4_ne                 , format: csv  , id: syn72388431.3  }
  - &jax_APOE4_Trem2_R47H_ne      { name: jax_APOE4_Trem2_R47H_ne      , format: csv  , id: syn72388432.2  }
  - &jax_Trem2_R47H_ne            { name: jax_Trem2_R47H_ne            , format: csv  , id: syn72388430.3  }
  - &jax_LOAD2_ne                 { name: jax_LOAD2_ne                 , format: csv  , id: syn76459553.1  }
  - &uci_3xTG_AD_ne               { name: uci_3xTG_AD_ne               , format: csv  , id: syn69058676.1  }
  - &uci_5xFAD_ne                 { name: uci_5xFAD_ne                 , format: csv  , id: syn69058679.1  }
  - &uci_ABCA7_ne                 { name: uci_ABCA7_ne                 , format: csv  , id: syn72388477.1  }
  - &uci_ABCA7_5xFAD_ne           { name: uci_ABCA7_5xFAD_ne           , format: csv  , id: syn72388476.2  }
  - &uci_Bin1_ne                  { name: uci_Bin1_ne                  , format: csv  , id: syn76459725.1  }
  - &uci_Bin1_5xFAD_ne            { name: uci_Bin1_5xFAD_ne            , format: csv  , id: syn76459724.1  }
  - &uci_Clu_ne                   { name: uci_Clu_ne                   , format: csv  , id: syn76459751.1  }
  - &uci_Clu_5xFAD_ne             { name: uci_Clu_5xFAD_ne             , format: csv  , id: syn76459744.1  }
  - &uci_Trem2_R47H_NSS_ne        { name: uci_Trem2_R47H_NSS_ne        , format: csv  , id: syn72388498.1  }
  - &uci_Trem2_R47H_NSS_5xFAD_ne  { name: uci_Trem2_R47H_NSS_5xFAD_ne  , format: csv  , id: syn72388499.2  }

datasets:
  - model_details:
      files:
        - <<: *model_metadata
        - <<: *model_genetic_modifications
        - <<: *pathology
        - <<: *biomarkers
        - <<: *immunohisto_measure_order
      final_format: json
      destination: *dest
      custom_transformations: transform_model_details
      column_rename:
        mouse_gene_symbol: modified_gene
        agedeath: age
        age_death: age
        measurement: value
        type: evidence_type
        model: name
        key: dataset_name
        items: evidence_type
      gx_nested_columns:
        - genetic_info
        - biomarkers
        - pathology
      gx_enabled: true

  - disease_correlation:
      files:
        - <<: *disease_correlation_results
        - <<: *model_metadata
        - <<: *model_genetic_modifications
      final_format: json
      destination: *dest
      custom_transformations: transform_disease_correlation

  - ui_config:
      files:
        - <<: *ui_config
      final_format: json
      destination: *dest
      gx_enabled: true
      gx_nested_columns:
        - columns

  - model_overview:
      files:
        - <<: *model_metadata
        - <<: *model_genetic_modifications
      final_format: json
      destination: *dest
      custom_transformations: transform_model_overview
      column_rename:
        mouse_gene_symbol: modified_gene
        model: name
      gx_enabled: true
      gx_nested_columns:
        - transcriptomics
        - disease_correlation
        - pathology
        - biomarkers
        - study_data
        - jax_strain

  - rna_de_aggregate:
      files:
        - <<: *genotype_label_map
        - <<: *mouse_gene_metadata
        - <<: *biodom_genes_mm
        - <<: *jax_5xFAD_de
        - <<: *jax_APOE4_Trem2_R47H_de
        - <<: *jax_LOAD2_de
        - <<: *uci_3xTG_AD_de
        - <<: *uci_5xFAD_de
        - <<: *uci_ABCA7_de
        - <<: *uci_Bin1_de
        - <<: *uci_Clu_de
        - <<: *uci_Trem2_R47H_NSS_de
      final_format: json
      destination: *dest
      custom_transformations: transform_rna_de_aggregate
      gx_enabled: true
      gx_nested_columns:
        - name
        - "4 months"
        - "12 months"
        - "18 months"
        - "24 months"

  - rna_de_individual:
      files:
        - <<: *genotype_label_map
        - <<: *mouse_gene_metadata
        - <<: *jax_APOE4_Trem2_R47H_ne
        - <<: *jax_APOE4_ne
        - <<: *jax_Trem2_R47H_ne
        - <<: *jax_LOAD2_ne
        - <<: *uci_ABCA7_5xFAD_ne
        - <<: *uci_ABCA7_ne
        - <<: *uci_Bin1_ne
        - <<: *uci_Bin1_5xFAD_ne
        - <<: *uci_Clu_ne
        - <<: *uci_Clu_5xFAD_ne
        - <<: *uci_Trem2_R47H_NSS_5xFAD_ne
        - <<: *uci_Trem2_R47H_NSS_ne
        - <<: *uci_3xTG_AD_ne
        - <<: *uci_5xFAD_ne
        - <<: *jax_5xFAD_ne
      final_format: json
      destination: *dest
      custom_transformations: transform_rna_de_individual
      gx_enabled: true
      gx_nested_columns:
        - data
