destination: &dest syn51498092
staging_path: ./staging
gx_folder: syn63141015
gx_table: syn63891939
datasets:
  - biomarkers:
      files:
        - name: biomarkers
          id: syn61250724
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: immunohisto_transform
      column_rename:
        agedeath: age
        age_death: age
        measurement: value
        type: evidence_type
        model: name

  - pathology:
      files:
        - name: pathology
          id: syn61357279
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: immunohisto_transform
      column_rename:
        agedeath: age
        age_death: age
        measurement: value
        type: evidence_type
        model: name

  - model_details:
      files:
        - name: model_info
          id: syn61378590
          format: csv
        - name: allele_info
          id: syn64618791
          format: csv
        - name: pathology
          id: syn61357279
          format: csv
        - name: biomarkers
          id: syn61250724
          format: csv
        - name: human_transgene_allele_map
          id: syn64846805
          format: csv
        - name: model_results_info
          id: syn68377668
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: transform_model_details
      column_rename:
        gene: modified_gene
        ensembl_id: human_ensembl_id
        agedeath: age
        age_death: age
        measurement: value
        type: evidence_type
        model: name
      gx_nested_columns:
        - genetic_info
        - biomarkers
        - pathology
      gx_enabled: true

  - disease_correlation:
      files:
        - name: disease_correlation_results
          id: syn65467849
          format: csv
        - name: model_info
          id: syn61378590
          format: csv
        - name: allele_info
          id: syn64618791
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: transform_disease_correlation
      column_rename:
        model: name

  - ui_config:
      files:
        - name: ui_config
          id: syn66527739
          format: json
      final_format: json
      destination: *dest
      gx_enabled: true
      gx_nested_columns:
        - columns

  - model_overview:
      files:
        - name: model_info
          id: syn61378590
          format: csv
        - name: model_results_info
          id: syn68377668
          format: csv
        - name: allele_info
          id: syn64618791
          format: csv
        - name: human_transgene_allele_map
          id: syn64846805
          format: csv
      final_format: json
      destination: *dest
      custom_transformations: transform_model_overview
      column_rename:
        gene: modified_gene
        ensembl_id: human_ensembl_id
        model: name

  - rna_de_aggregate:
      files:
        - name: rnaseq_genotype_label_map
          id: syn69014401
          format: csv
        - name: mouse_gene_metadata
          id: syn51615422
          format: json
        - name: model_info
          id: syn61378590
          format: csv
        - name: biodom_genes_mm
          id: syn66351272
          format: csv
        - name: Jax.IU.Pitt_5XFAD_differential_expression
          id: syn69058660
          format: csv
        - name: Jax.IU.Pitt_APOE4.Trem2.R47H_differential_expression
          id: syn69693082
          format: csv
        - name: UCI_3xTg-AD_differential_expression
          id: syn69058661
          format: csv
        - name: UCI_5XFAD_differential_expression
          id: syn69058664
          format: csv
        - name: UCI_ABCA7_differential_expression
          id: syn69058663
          format: csv
        - name: UCI_Trem2-R47H_NSS_differential_expression
          id: syn69058662
          format: csv
      final_format: json
      provenance:
        - syn69014401
        - syn51615422
        - syn61378590
        - syn66351272
        - syn69058660
        - syn69693082
        - syn69058661
        - syn69058664
        - syn69058663
        - syn69058662
      destination: *dest
      custom_transformations: transform_rna_de_aggregate

  - rna_de_individual:
      files:
        - name: rnaseq_genotype_label_map
          id: syn69014401
          format: csv
        - name: mouse_gene_metadata
          id: syn51615422
          format: json
        - name: Jax.IU.Pitt_5XFAD_normalized_expression
          id: syn69693095
          format: csv
        - name: UCI_3xTg-AD_normalized_expression
          id: syn69693094
          format: csv
        - name: UCI_ABCA7_normalized_expression
          id: syn69693096
          format: csv
        - name: Jax.IU.Pitt_APOE4.Trem2.R47H_normalized_expression
          id: syn69693097
          format: csv
        - name: UCI_5XFAD_normalized_expression
          id: syn69693098
          format: csv
        - name: UCI_Trem2-R47H_NSS_normalized_expression
          id: syn69693099
          format: csv
      final_format: json
      provenance:
        - syn69014401
        - syn51615422
        - syn69693095
        - syn69693094
        - syn69693096
        - syn69693097
        - syn69693098
        - syn69693099
      destination: *dest
      custom_transformations: transform_rna_de_individual
