destination: &dest syn74766141 # preprod
staging_path: ./staging/xqtl
gx_folder: syn74766208         # preprod
gx_table: syn74766241          # preprod

# Reusable file reference anchors used by datasets below.
files:
  # Metadata & Configuration
  - &ui_config                    { name: ui_config                    , format: json , id: syn77143753 }
  # QTL Results
  # Expression Results


datasets:
  - ui_config:
      files:
        - <<: *ui_config
      final_format: json
      destination: *dest
      gx_enabled: false