# Compare MD5 hashes of files in the specified target branch against the 'dev' branch
name: compare-md5

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        feature_branch:
            description: 'Branch to run workflow on'
            required: true
            default: 'dev'
jobs:
  compare-md5:
    env:
      SYNAPSE_TOKEN: ${{ secrets.SYNAPSE_PAT }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
    steps:
      - uses: actions/checkout@v4
        with:
            ref: ${{ github.event.inputs.feature_branch }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: test data processing and upload in target branch
        run: |
          if [ -z "${{ secrets.SYNAPSE_PAT }}" ]; then
            echo "❌ SYNAPSE_PAT secret is not set. Exiting."
            exit 1
          fi
          adt test_config.yaml --upload --platform GITHUB --run_id ${{ github.run_id }} --token ${{ secrets.SYNAPSE_PAT }}
      - name: Get MD5 hashes in feature branch
        id: feature_md5
        run: |
          feature_output=$(python compare_md5.py)
          echo "::set-output name=feature_output::$feature_output"
      # Checkout the repository again to switch to the 'dev' branch for comparison
      - uses: actions/checkout@v4
        with:
            ref: dev
      - name: test data processing and upload in dev branch
        run: adt test_config.yaml --upload --platform GITHUB --run_id ${{ github.run_id }} --token ${{secrets.SYNAPSE_PAT}}
      - name: Get MD5 hashes in dev branch
        id: dev_md5
        run: |
          dev_output=$(python compare_md5.py)
          echo "::set-output name=dev_output::$dev_output"
      - name: Validate MD5 hash consistency
        run: |
          echo "Feature branch MD5s: ${{ steps.feature_md5.outputs.feature_output }}"
          echo "Dev branch MD5s: ${{ steps.dev_md5.outputs.dev_output }}"

          if [ "${{ steps.feature_md5.outputs.feature_output }}" != "${{ steps.dev_md5.outputs.dev_output }}" ]; then
            echo "❌ MD5 hashes do not match!"
            echo "Feature branch MD5s: ${{ steps.feature_md5.outputs.feature_output }}"
            echo "Dev branch MD5s: ${{ steps.dev_md5.outputs.dev_output }}"
            exit 1
          else
            echo "✅ MD5 hashes match!"
          fi
